on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Lint code
      run: npm run lint
    # - name: Test code
    #   run: npm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

  test_workflow:
    runs-on: ubuntu-latest
    name: A job to say hello
    needs: lint_and_test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        with:
          python: true
          javascript: true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectFolder: 'src/'
